/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthProfileImport } from './routes/_auth/profile'
import { Route as AuthMyHotelsImport } from './routes/_auth/my-hotels'
import { Route as AuthMyBookingsImport } from './routes/_auth/my-bookings'
import { Route as AuthMyHotelsAddImport } from './routes/_auth/my-hotels_.add'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMyHotelsRoute = AuthMyHotelsImport.update({
  path: '/my-hotels',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMyBookingsRoute = AuthMyBookingsImport.update({
  path: '/my-bookings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMyHotelsAddRoute = AuthMyHotelsAddImport.update({
  path: '/my-hotels/add',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_auth/my-bookings': {
      preLoaderRoute: typeof AuthMyBookingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/my-hotels': {
      preLoaderRoute: typeof AuthMyHotelsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/my-hotels/add': {
      preLoaderRoute: typeof AuthMyHotelsAddImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthMyBookingsRoute,
    AuthMyHotelsRoute,
    AuthProfileRoute,
    AuthMyHotelsAddRoute,
  ]),
  AboutRoute,
  LoginRoute,
  RegisterRoute,
])

/* prettier-ignore-end */
